#include <iostream>

struct Foo {
    void print_value(int value) { std::cout << value; }
};

void print_value(int value) { std::cout << value; }

template <typename T> void print_value2(T value) { std::cout << value << "\n"; }

void print_value2(double value) { std::cout << value << "\n"; }

void print_value2(int value) { std::cout << value << "\n"; }

int add(int x, int y) { return x + y; }

int subtract(int x, int y) { return x - y; }

int multiply(int x, int y) { return x * y; }

int main() {
    // "binding" is the process of associating names with properties like type, value, memory address, whether it's a variable/function
    // "function binding" or "method binding" determines which function definition is associated with a function call
    // "dispatching" is the process of actually invoking a bound function
    // c++ usually combines the terms binding and dispatching

    // direct calls to non-member functions or non-virtual member functions can be dispatched at compile time (early/static binding); the compiler/linker generates instructions to jump directly to the address of the function
    print_value(5);

    Foo f {};
    f.print_value(5);

    /*
    the assembly for the print_value(5) generated by clang x86_64 looks approximately like:
    ```
        mov     edi, 5      ; copy argument 5 into edi register in preparation for function call
        call    print_value(int)    ; directly call print_value(int)
    ```
    */

    // calls to overloaded functions and function templates are also resolved at compile time:
    print_value2(5);
    print_value2<>(5);

    // a sample calculator that uses early binding:
    {
        int x {};
        std::cout << "Enter a number: ";
        std::cin >> x;

        int y {};
        std::cout << "Enter another number: ";
        std::cin >> y;

        int op {};
        std::cout << "Enter an operator (0=add, 1=subtract, 2=multiply): ";
        std::cin >> op;

        int result {};
        switch (op) {
        case 0:
            result = add(x, y);
            break;
        case 1:
            result = subtract(x, y);
            break;
        case 2:
            result = multiply(x, y);
            break;
        default:
            std::cout << "Invalid operator\n";
            return 1;
        }

        std::cout << "The answer is: " << result << "\n";
    }
    // the switch statement makes it so which function actually gets called isn't determined until runtime, but that's a path of execution issue, not a binding issue

    // dynamic/late binding happens whenever the compiler can't resolve the function call until runtime (as in, can't be resolved using static type information alone); c++ also uses the term late binding to refer to any function call where the actual function being called isn't known by the compiler or linker at the point where the function call is actually being made

    // function pointers use late binding:
    auto fcn { print_value };
    fcn(5);

    /*
    the clang x86_64 assembly for the fcn(5) call looks like:
    ```
        lea     rax, [rip + print_value(int)]   ; determine address of print_value and put it into rax register
        mov     qword ptr [rbp - 8], rax        ; move value in rax register into memory for variable fcn

        mov     edi, 5              ; copy argument 5 into edi register in preparation for function call
        call    qword ptr [rbp - 8] ; invoke the function at the address held by variable fcn
    ```
    */
    // a sample calculator that uses late binding:
    {
        int x {};
        std::cout << "Enter a number: ";
        std::cin >> x;

        int y {};
        std::cout << "Enter another number: ";
        std::cin >> y;

        int op {};
        std::cout << "Enter an operator (0=add, 1=subtract, 2=multiply): ";
        std::cin >> op;

        using FcnPtr = int (*)(int, int);
        FcnPtr fcn { nullptr };

        switch (op) {
        case 0:
            fcn = add;
            break;
        case 1:
            fcn = subtract;
            break;
        case 2:
            fcn = multiply;
            break;
        default:
            std::cout << "Invalid operator\n";
            return 1;
        }

        std::cout << "The answer is: " << fcn(x, y) << "\n";
    }

    // late binding involves an extra step of indirection of reading the address held in the pointer then jumping to it

    return 0;
}